import { existsSync } from 'node:fs';
import { defineConfig, env } from 'prisma/config';

// Local development reads the repo-root .env (generated by scripts/dev-env.sh).
// Deployed environments inject DATABASE_URL directly.
const rootEnv = new URL('../../.env', import.meta.url);
if (!process.env.DATABASE_URL && existsSync(rootEnv)) process.loadEnvFile(rootEnv);

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: { path: 'prisma/migrations' },
  datasource: { url: env('DATABASE_URL') },
});
