import { existsSync } from 'node:fs';
import { defineConfig } from 'prisma/config';

// Local development reads the repo-root .env (generated by scripts/dev-env.sh).
// Deployed environments inject DATABASE_URL directly.
const rootEnv = new URL('../../.env', import.meta.url);
if (!process.env.DATABASE_URL && existsSync(rootEnv)) process.loadEnvFile(rootEnv);

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: { path: 'prisma/migrations' },
  // Not env(): it throws on load, and `prisma generate` (build, CI) needs no database.
  datasource: { url: process.env.DATABASE_URL },
});
