#!/usr/bin/env bash
# Creates ./.env for local development with freshly generated secrets.
# Never commit .env. Re-running keeps an existing file untouched.
set -euo pipefail
cd "$(dirname "$0")/.."

if [[ -f .env ]]; then
  echo ".env already exists; leaving it untouched."
  exit 0
fi

rand() { openssl rand -base64 "$1" | tr -d '\n/+=' | head -c "$2"; }
PG_PASS=$(rand 32 32)
REDIS_PASS=$(rand 32 32)

umask 077
cat > .env <<ENV
# Generated by scripts/dev-env.sh — local development only.
NODE_ENV=development
LOG_LEVEL=debug

POSTGRES_PASSWORD=${PG_PASS}
REDIS_PASSWORD=${REDIS_PASS}
DATABASE_URL=postgresql://hubmine:${PG_PASS}@127.0.0.1:5432/hubmine?schema=public
REDIS_URL=redis://:${REDIS_PASS}@127.0.0.1:6379/0

API_PORT=3001
WEB_ORIGIN=http://localhost:3000
COOKIE_SECURE=false
JWT_ACCESS_SECRET=$(rand 64 64)
JWT_ACCESS_TTL_SECONDS=900
REFRESH_TTL_DAYS=30
SECRETS_ENCRYPTION_KEY=$(openssl rand -base64 32)

NODE_NAME=local
DOCKER_SOCKET_PATH=/var/run/docker.sock
MC_PUBLIC_HOST=localhost
MC_BIND_IP=0.0.0.0
MC_PORT_RANGE=25565-25664
MC_UID=1000
MC_GID=1000
NODE_SAFE_RATIO=0.85
# Dev override: allow a daemon without userns-remap (never in production).
DOCKER_REQUIRE_USERNS=true
ENV
echo "Created .env (mode 600)."
